here::here()
require(ggplot2)
require(zoo)
require(openxlsx)
require(bootstrap)
require(MSGARCH)
require(gtrendsR)
require(formattable)
require(DT)
require(kableExtra)
require(scales)
require(zoo)
require(xts)
require(dplyr)
require(formattable)
require(dygraphs)
require(readxl)
require(alfred)
require(httr)
require(ecb)
require(tableHTML)
require(reshape)
require(tidyverse)
require(missForest)
require(maps)
require(PortfolioAnalytics)
require(magrittr)


################################################################################
# source code
################################################################################
source('Function/getHisDataAV.R')
source('Function/getFXECB.R')
source('Function/getRisk.R')
source('Function/bootstrapRisk.R')
source('Function/filter.R')
source('Function/utility.R')