---
title: "<center><div class='mytitle'> MY PORTFOLIO RISK ANALYSIS</div></center>"
date: <center>'`r format(Sys.time(), "%d %B, %Y")`'</center>
css: style.css
output: 
  html_document:
   #  toc: FALSE
   includes:
    before_body: header.html
    after_body: footer.html
---


```{r echo=T, results='hide', echo=FALSE}
setwd(here::here())
suppressMessages(source('profileRep.R'))
load("Data/Portfolio_Market.RData")
load("Data/portRisk.RData")
```
<center>
```{r include = TRUE, echo=FALSE, fig.align='center'}

ts_a2 <-  xts::xts(x = cbind(-100 *portRisk$`VaR bootstrap 95Quantile`,
                            -100 *portRisk$VaR_bootstrap, 
                            -100 *portRisk$`VaR bootstrap 05Quantile`,
                            100 * portRisk$VolaN1_MSGARCH), 
                  order.by = as.Date(portRisk$CloseDate))
ts_a2 <- ts_a2["2019-02-20::",]
names(ts_a2) <-  c("lwr", "fit", "upr","VolaN1_MSGARCH")

VaREuro <- dp$position$Value[dp$position$AlphaVantage=='Port']*tail(ts_a2$fit,1)/100
titleVaR <- paste0("Portfolio VaR ",round(tail(ts_a2$fit,1),2), '% - ',round(VaREuro,2),'€')

dygraphs::dygraph(ts_a2, main = titleVaR, width = 1800) %>%
  dyAxis("x", drawGrid = FALSE) %>%
  dyAxis("y", label='VaR in %', drawGrid = FALSE) %>%
  dySeries(c("lwr", "fit", "upr"), label = "VaR 0.95") %>%
  dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")) %>%
  dySeries("VolaN1_MSGARCH", axis = 'y2') %>%
  dyAxis("y2", label="VolaN1_MSGARCH", drawGrid = FALSE) %>%
  dyRangeSelector(height = 20)
```

```{r include = TRUE, echo=FALSE, fig.align='center'}
ts_a <-  xts::xts(x = cbind(-100 *portRisk$`ES bootstrap 95Quantile`,
                            -100 *portRisk$`ES bootstrap`, 
                            -100 *portRisk$`ES bootstrap 05Quantile`,
                      100 * portRisk$VolaN1_MSGARCH), 
                 order.by = as.Date(portRisk$CloseDate))
names(ts_a) <-  c("lwr", "fit", "upr","VolaN1_MSGARCH")
ts_a <- ts_a["2019-02-20::",]

ESEuro <- dp$position$Value[dp$position$AlphaVantage=='Port']*tail(ts_a$fit,1)/100
titleES <- paste0("Portfolio ES ",round(tail(ts_a$fit,1),2), '% - ',round(ESEuro,2),'€')
dygraphs::dygraph(ts_a, main = titleES, width = 1800) %>%
  dyAxis("x", drawGrid = FALSE) %>%
  dyAxis("y", label='ES in %', drawGrid = FALSE) %>%
  dySeries(c("lwr", "fit", "upr"), label = "ES 0.95") %>%
  dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")) %>%
  dySeries("VolaN1_MSGARCH", axis = 'y2') %>%
  dyAxis("y2", label="VolaN1_MSGARCH", drawGrid = FALSE) %>%
  dyRangeSelector(height = 20)
```
</center>

<p style="text-align: center;">  Open Positions: </p>

```{r include = TRUE, echo=FALSE, fig.align='center'}
dp$risk %>% subset(dp$risk$SharePortfolio>0.0001 | dp$risk$Name == 'Portfolio:'
                   ,select=names(dp$risk)[c(2:18,27,28,37,40,42,43,44,45)]) %>%
  mutate(std_log_returns = std_log_returns * 100) %>% 
  mutate(std_log_returns_1Y = std_log_returns_1Y * 100) %>%
  mutate(VolaN1_MSGARCH = VolaN1_MSGARCH * 100) %>%
  dplyr::rename(`ind VaR MSGARCH`=ind_VaR_MSGARCH)%>%
  dplyr::rename(`250D CAPM Return`=`250D.CAPM.Return`)%>%
  dplyr::rename(`250D log Return`=`250D.logReturn`)%>%
  dplyr::rename(`Jensen Alpha`=Jensen.Alpha)%>%
  dplyr::rename(`std log returns`=std_log_returns)%>%  
  dplyr::rename(`std log returns 1Y`=std_log_returns_1Y)%>%  
  dplyr::rename(`std N1 MSGARCH`= VolaN1_MSGARCH)%>%
  dplyr::rename(`ES MSGARCH`= ES_MSGARCH)%>%
  plyr::arrange(!SharePortfolio)  -> risk.Table 

#c(-1,-25,-26,-29,-30,-32,-33,-39,-40,-42)
risk.Table <- replace(risk.Table, is.na(risk.Table),0)

datatable(risk.Table,
            extensions = 'Buttons', options = list(pageLength = 100,
    dom = 'Bfrtip',
    buttons = list('copy', 'csv', 'excel', 'pdf', 'print',
    list(extend = 'colvis',visible=F, targets= 0, columns = c(3:dim(risk.Table)[2])))
        )) %>%
  formatRound('Value', digits = 0, interval = 3, mark = " ")%>%
  formatPercentage('SharePortfolio', 1) %>%
  formatStyle('SharePortfolio', background = color_from_middle(risk.Table$SharePortfolio,'pink','lightblue')) %>%
  formatRound('Beta', digits = 2, interval = 3, mark = " ")%>%
  formatStyle('Beta', background = color_from_middle(risk.Table$Beta,'pink','pink')) %>%
  formatRound('Beta1Y', digits = 2, interval = 3, mark = " ")%>%
  formatStyle('Beta1Y', background = color_from_middle(risk.Table$Beta1Y,'pink','pink')) %>%
  formatPercentage('250D log Return', 1) %>%
  formatStyle('250D log Return', background = color_from_middle(risk.Table$`250D log Return`,'pink','pink')) %>%
  formatPercentage('250D CAPM Return', 1) %>%
  formatStyle('250D CAPM Return', background = color_from_middle(risk.Table$`250D CAPM Return`,'pink','pink')) %>%
    formatRound('Jensen Alpha', digits = 2, interval = 3, mark = " ")%>%
  formatStyle('Jensen Alpha', background = color_from_middle(risk.Table$`Jensen Alpha`,'pink','lightblue')) %>%
 formatRound('std log returns', digits = 1, interval = 3, mark = " ")%>%
 formatStyle('std log returns', background = color_from_middle(risk.Table$`std log returns`,'pink','pink')) %>%
 formatRound('std log returns 1Y', digits = 1, interval = 3, mark = " ")%>%
 formatStyle('std log returns 1Y', background = color_from_middle(risk.Table$`std log returns 1Y`,'pink','pink')) %>%
    formatRound('std N1 MSGARCH', digits = 1, interval = 3, mark = " ")%>%
  formatStyle('std N1 MSGARCH', background = color_from_middle(risk.Table$`std N1 MSGARCH`,'pink','pink')) %>%
  formatPercentage('VaR Normal std1Y', 1) %>%
  formatStyle('VaR Normal std1Y', background = color_from_middle(risk.Table$`VaR Normal std1Y`,'pink','pink')) %>%
  formatPercentage('VaR Normal', 1) %>%
  formatStyle('VaR Normal', background = color_from_middle(risk.Table$`VaR Normal`,'pink','pink')) %>%
  formatPercentage('VaR HS 1Y', 1) %>%
  formatStyle('VaR HS 1Y', background = color_from_middle(risk.Table$`VaR HS 1Y`,'pink','pink')) %>%
#  formatPercentage('VaR Share', 1) %>%
#  formatStyle('VaR Share', background = color_from_middle(risk.Table$`VaR_Share`,'pink','pink')) %>%
  formatPercentage('ES MSGARCH', 1) %>%
  formatStyle('ES MSGARCH', background = color_from_middle(risk.Table$`ES MSGARCH`,'pink','pink')) %>%
    formatPercentage('ES bootstrap', 1) %>%
  formatStyle('ES bootstrap', background = color_from_middle(risk.Table$`ES bootstrap`,'pink','pink')) %>%
  formatPercentage('VaR_bootstrap', 1) %>%
  formatStyle('VaR_bootstrap', background = color_from_middle(risk.Table$`VaR_bootstrap`,'pink','pink')) %>%
formatPercentage('VaR Share', 1) %>%
formatStyle('VaR Share', background = color_from_middle(risk.Table$`VaR Share`,'pink','pink')) %>%
    formatPercentage('ind VaR MSGARCH', 1) %>%
  formatStyle('ind VaR MSGARCH', background = color_from_middle(risk.Table$`ind VaR MSGARCH`,'pink','pink'))%>%
    formatPercentage('component VaR', 1) %>%
  formatStyle('component VaR', background = color_from_middle(risk.Table$`component VaR`,'pink','pink'))

##dp$risk %>% subset((dp$risk$SharePortfolio==0 | is.na(dp$risk$SharePortfolio))& dp$risk$Name != 'Portfolio:'
```

<p style="text-align: center;">  Overview: </p>

```{r include = TRUE, echo=FALSE, fig.align='center'}

dp$risk %>% subset(!(dp$risk$SharePortfolio>0.0001) | dp$risk$Name == 'Portfolio:'
                   ,select=names(dp$risk)[c(2:18,27,28,37,40,42,43,44,45)]) %>%
  mutate(std_log_returns = std_log_returns * 100) %>% 
  mutate(std_log_returns_1Y = std_log_returns_1Y * 100) %>%
  mutate(VolaN1_MSGARCH = VolaN1_MSGARCH * 100) %>%
  dplyr::rename(`ind VaR MSGARCH`=ind_VaR_MSGARCH)%>%
  dplyr::rename(`250D CAPM Return`=`250D.CAPM.Return`)%>%
  dplyr::rename(`250D log Return`=`250D.logReturn`)%>%
  dplyr::rename(`Jensen Alpha`=Jensen.Alpha)%>%
  dplyr::rename(`std log returns`=std_log_returns)%>%  
  dplyr::rename(`std log returns 1Y`=std_log_returns_1Y)%>%  
  dplyr::rename(`std N1 MSGARCH`= VolaN1_MSGARCH)%>%
  dplyr::rename(`ES MSGARCH`= ES_MSGARCH)%>%
  plyr::arrange(!SharePortfolio)  -> risk.Table 

#c(-1,-25,-26,-29,-30,-32,-33,-39,-40,-42)
risk.Table <- replace(risk.Table, is.na(risk.Table),0)

datatable(risk.Table,extensions = 'Buttons', 
          options = list(pageLength = 100,dom = 'Bfrtip',
            buttons = list('copy', 'csv', 'excel', 'pdf', 'print',
            list(extend = 'colvis', visible=F, columns = c(3:dim(risk.Table)[2]))))
          ) %>%
  formatRound('Value', digits = 0, interval = 3, mark = " ")%>%
  formatPercentage('SharePortfolio', 1) %>%
  formatStyle('SharePortfolio', background = color_from_middle(risk.Table$SharePortfolio,'pink','lightblue')) %>%
  formatRound('Beta', digits = 2, interval = 3, mark = " ")%>%
  formatStyle('Beta', background = color_from_middle(risk.Table$Beta,'pink','pink')) %>%
  formatRound('Beta1Y', digits = 2, interval = 3, mark = " ")%>%
  formatStyle('Beta1Y', background = color_from_middle(risk.Table$Beta1Y,'pink','pink')) %>%
  formatPercentage('250D log Return', 1) %>%
  formatStyle('250D log Return', background = color_from_middle(risk.Table$`250D log Return`,'pink','pink')) %>%
  formatPercentage('250D CAPM Return', 1) %>%
  formatStyle('250D CAPM Return', background = color_from_middle(risk.Table$`250D CAPM Return`,'pink','pink')) %>%
    formatRound('Jensen Alpha', digits = 2, interval = 3, mark = " ")%>%
  formatStyle('Jensen Alpha', background = color_from_middle(risk.Table$`Jensen Alpha`,'pink','lightblue')) %>%
 formatRound('std log returns', digits = 1, interval = 3, mark = " ")%>%
 formatStyle('std log returns', background = color_from_middle(risk.Table$`std log returns`,'pink','pink')) %>%
 formatRound('std log returns 1Y', digits = 1, interval = 3, mark = " ")%>%
 formatStyle('std log returns 1Y', background = color_from_middle(risk.Table$`std log returns 1Y`,'pink','pink')) %>%
    formatRound('std N1 MSGARCH', digits = 1, interval = 3, mark = " ")%>%
  formatStyle('std N1 MSGARCH', background = color_from_middle(risk.Table$`std N1 MSGARCH`,'pink','pink')) %>%
  formatPercentage('VaR Normal std1Y', 1) %>%
  formatStyle('VaR Normal std1Y', background = color_from_middle(risk.Table$`VaR Normal std1Y`,'pink','pink')) %>%
  formatPercentage('VaR Normal', 1) %>%
  formatStyle('VaR Normal', background = color_from_middle(risk.Table$`VaR Normal`,'pink','pink')) %>%
  formatPercentage('VaR HS 1Y', 1) %>%
  formatStyle('VaR HS 1Y', background = color_from_middle(risk.Table$`VaR HS 1Y`,'pink','pink')) %>%
#  formatPercentage('VaR Share', 1) %>%
#  formatStyle('VaR Share', background = color_from_middle(risk.Table$`VaR_Share`,'pink','pink')) %>%
  formatPercentage('ES MSGARCH', 1) %>%
  formatStyle('ES MSGARCH', background = color_from_middle(risk.Table$`ES MSGARCH`,'pink','pink')) %>%
    formatPercentage('ES bootstrap', 1) %>%
  formatStyle('ES bootstrap', background = color_from_middle(risk.Table$`ES bootstrap`,'pink','pink')) %>%
  formatPercentage('VaR_bootstrap', 1) %>%
  formatStyle('VaR_bootstrap', background = color_from_middle(risk.Table$VaR_bootstrap,'pink','pink')) %>%
formatPercentage('VaR Share', 1) %>%
formatStyle('VaR Share', background = color_from_middle(risk.Table$`VaR Share`,'pink','pink')) %>%
    formatPercentage('ind VaR MSGARCH', 1) %>%
  formatStyle('ind VaR MSGARCH', background = color_from_middle(risk.Table$`ind VaR MSGARCH`,'pink','pink'))
```


