---
title: "<center><div class='mytitle'> MY PORTFOLIO PERFORMANCE ANALYSIS</div></center>"
date: <center>'`r format(Sys.time(), "%d %B, %Y")`'</center>
css: style.css
output: 
  html_document:
   #  toc: FALSE
   includes:
    before_body: header.html
    after_body: footer.html
header-includes:
- \usepackage{booktabs}
- \usepackage{sectsty} \sectionfont{\centering \emph}
---

```{r echo=T, results='hide', echo=FALSE}
#setwd(here::here())
#suppressMessages(source('profileRep.R'))
#load("Data/Portfolio_Market.RData")
```
<p style="text-align: center;"> # Cboe Volatility Index: </p>
<center>
```{r include = TRUE, echo=FALSE, fig.align='center'}

# PerformanceAnalytics::charts.PerformanceSummary(R = dp$portfolio_returns)


textMain <- paste0(as.character(end(dm$logRetPort)),' Daily log return: ' , round(tail(dm$logRetPort,1)*100,2),'% ',
       'Monthly log return: ' , 
       round(sum(dm$logRetPort[paste0(Sys.Date()-30,'/',Sys.Date())])*100,2),'% ',   unlist(strsplit(as.character(end(dp$vola$VIX))," ")),"VIX S&P 500 ",round(tail(dp$vola$VIX,1),4),"Pt. Change",round(diff(tail(dp$vola$VIX,2))[2],4))

close360d <- as.vector(window(dm$adjClosePort, start=Sys.Date()-364, end = Sys.Date())[1])
ts_a <- 
xts::merge.xts(dm$adjClosePort[paste0(Sys.Date()-360,'/',Sys.Date())] /close360d, 
               dp$vola$VIX[paste0(Sys.Date()-360,'/',Sys.Date())])
names(ts_a) <- c("portfolio", "VIX")

dygraphs::dygraph(ts_a, main = textMain, width = 1800) %>%
  dySeries("portfolio") %>%
  dySeries("VIX", axis = 'y2') %>%
  dyRangeSelector(height = 20)
```

<p style="text-align: center;">  Performance aggregated by category: </p>
```{r include = TRUE, echo=FALSE}
replace(dp$position, is.na(dp$position),0) %>% 
  subset(dp$position$SharePortfolio>0.001,
         select=c('Category',
                  'SharePortfolio', 
                  'Value',
                  'ab_return_D1',
                  'return_D1',
                  'CAPM_return_D1',
                  'ab_return_D5',
                  'return_D5',
                  'CAPM_return_D5',
                  'ab_return_D23',
                  'return_D23',
                  'CAPM_return_D23',
                  'ab_return_D125',
                  'return_D125',
                  'CAPM_return_D125',
                  'ab_return_D250',
                  'return_D250',
                  'CAPM_return_D250')) %>%
  mutate(CAPM_return_D1=SharePortfolio * CAPM_return_D1,
         CAPM_return_D5=SharePortfolio * CAPM_return_D5,
         CAPM_return_D23=SharePortfolio * CAPM_return_D23,
         CAPM_return_D125=SharePortfolio * CAPM_return_D125,
         CAPM_return_D250=SharePortfolio * CAPM_return_D250,
         return_D1 = SharePortfolio * return_D1,
         return_D5 = SharePortfolio * return_D5,
         return_D23 = SharePortfolio * return_D23,
         return_D125 = SharePortfolio * return_D125,
         return_D250 = SharePortfolio * return_D250
  )%>%
  group_by(Category) %>% summarize(
    SharePortfolio=sum(SharePortfolio),
    Value=sum(Value),
    ab_return_D1= sum(ab_return_D1),
    return_D1 = sum(return_D1),
    CAPM_return_D1 = sum(CAPM_return_D1),
    ab_return_D5 = sum(ab_return_D5),
    return_D5 = sum(return_D5),
    CAPM_return_D5 = sum(CAPM_return_D5),
    ab_return_D23 = sum(ab_return_D23),
    return_D23 = sum(return_D23),
    CAPM_return_D23 = sum(CAPM_return_D23),
    ab_return_D125 = sum(ab_return_D125),
    return_D125 = sum(return_D125),
    CAPM_return_D125 = sum(CAPM_return_D125),
    ab_return_D250 = sum(ab_return_D250),
    return_D250 = sum(return_D250),
    CAPM_return_D250 = sum(CAPM_return_D250)) -> t2

t2 %>%
  datatable(extensions = 'Buttons', options = list(pageLength = 100,
                                                   columnDefs = list(list(visible=FALSE, targets=c(6:18))),
                                                   dom = 'Bfrtip',
                                                   buttons = list('copy', 'csv', 'excel', 'pdf', 'print',
                                                                  list(extend = 'colvis',visible=F, targets= 0))
  )) %>%
  formatCurrency('Value', '\U20AC', digits = 0) %>%
  formatPercentage('SharePortfolio', 1) %>%
  formatStyle('SharePortfolio', background = color_from_middle(t2$SharePortfolio,'lightblue','lightblue')) %>%
  formatPercentage('return_D1', 2) %>%
  formatStyle('return_D1', background = color_from_middle(t2$return_D1,'pink','lightgreen'))%>%
  formatPercentage('CAPM_return_D1', 2)%>%
  formatStyle('CAPM_return_D1', background = color_from_middle(t2$CAPM_return_D1,'pink','lightgreen'))%>%
  formatCurrency('ab_return_D1', '\U20AC', digits = 0)  %>%
  
  formatPercentage('return_D5', 2)%>%
  formatStyle('return_D5', background = color_from_middle(t2$return_D5,'pink','lightgreen'))%>%
  formatCurrency('ab_return_D5', '\U20AC', digits = 0)  %>%
  formatPercentage('CAPM_return_D5', 2)%>%
  formatStyle('CAPM_return_D5', background = color_from_middle(t2$CAPM_return_D5,'pink','lightgreen'))%>%
  formatCurrency('ab_return_D5', '\U20AC', digits = 0)  %>%
  
  formatPercentage('return_D23', 2)%>%
  formatStyle('return_D23', background = color_from_middle(t2$return_D23,'pink','lightgreen'))%>%
  formatCurrency('ab_return_D23', '\U20AC', digits = 0) %>%
  formatPercentage('CAPM_return_D23', 2)%>%
  formatStyle('CAPM_return_D23', background = color_from_middle(t2$CAPM_return_D23,'pink','lightgreen'))%>%
  formatCurrency('ab_return_D23', '\U20AC', digits = 0)  %>%
  
  formatPercentage('return_D125', 2)%>%
  formatStyle('return_D125', background = color_from_middle(t2$return_D125,'pink','lightgreen'))%>%
  formatCurrency('ab_return_D125', '\U20AC', digits = 0)   %>%
  formatPercentage('CAPM_return_D125', 2)%>%
  formatStyle('CAPM_return_D125', background = color_from_middle(t2$CAPM_return_D125,'pink','lightgreen'))%>%
  formatCurrency('ab_return_D125', '\U20AC', digits = 0)  %>%
  
  formatPercentage('return_D250', 2)%>%
  formatStyle('return_D250', background = color_from_middle(t2$return_D250,'pink','lightgreen'))%>%
  formatCurrency('ab_return_D250', '\U20AC', digits = 0) %>%
  formatPercentage('CAPM_return_D250', 2)%>%
  formatStyle('CAPM_return_D250', background = color_from_middle(t2$CAPM_return_D250,'pink','lightgreen'))%>%
  formatCurrency('ab_return_D250', '\U20AC', digits = 0)
```

```{r include = TRUE, echo=FALSE}
replace(dp$position, is.na(dp$position),0) %>% 
  subset((dp$position$SharePortfolio>0.001 &
            !is.na(dp$position$SharePortfolio)) | dp$position$Name == 'Portfolio:'| 
           dp$position$Category == 'Benchmark' ,
                      select=c('Name','Category',
                  'SharePortfolio', 
                  'Value',
                  'ab_return_D1',
                  'return_D1',
                  'CAPM_return_D1',
                  'jensen_alpha_D1',
                  'ab_return_D5',
                  'return_D5',
                  'CAPM_return_D5',
                  'jensen_alpha_D5',
                  'ab_return_D23',
                  'return_D23',
                  'CAPM_return_D23',
                  'jensen_alpha_D23',
                  'ab_return_D125',
                  'return_D125',
                  'CAPM_return_D125',
                  'jensen_alpha_D125',
                  'ab_return_D250',
                  'return_D250',
                  'CAPM_return_D250',
                  'jensen_alpha_D250')) -> t2

t2 %>%
  datatable(extensions = 'Buttons', options = list(pageLength = 100,
                                                   columnDefs = list(list(visible=FALSE, targets=c(6:18))),
                                                   dom = 'Bfrtip',
                                                   buttons = list('copy', 'csv', 'excel', 'pdf', 'print',
                                                                  list(extend = 'colvis',visible=F, targets= 0))
  )) %>%
  formatCurrency('Value', '\U20AC', digits = 0) %>%
  formatPercentage('SharePortfolio', 1) %>%
  formatStyle('SharePortfolio', background = color_from_middle(t2$SharePortfolio,'lightblue','lightblue')) %>%
  formatPercentage('return_D1', 2) %>%
  formatStyle('return_D1', background = color_from_middle(t2$return_D1,'pink','lightgreen'))%>%
  formatPercentage('CAPM_return_D1', 2)%>%
  formatStyle('CAPM_return_D1', background = color_from_middle(t2$CAPM_return_D1,'pink','lightgreen'))%>%
  formatPercentage('jensen_alpha_D1', 2)%>%
  formatStyle('jensen_alpha_D1', background = color_from_middle(t2$jensen_alpha_D1,'pink','lightgreen'))%>%
  formatCurrency('ab_return_D1', '\U20AC', digits = 0)  %>%
  
  formatPercentage('return_D5', 2)%>%
  formatStyle('return_D5', background = color_from_middle(t2$return_D5,'pink','lightgreen'))%>%
  formatCurrency('ab_return_D5', '\U20AC', digits = 0)  %>%
  formatPercentage('CAPM_return_D5', 2)%>%
  formatStyle('CAPM_return_D5', background = color_from_middle(t2$CAPM_return_D5,'pink','lightgreen'))%>%
    formatPercentage('jensen_alpha_D5', 2)%>%
  formatStyle('jensen_alpha_D5', background = color_from_middle(t2$jensen_alpha_D5,'pink','lightgreen'))%>%
  formatCurrency('ab_return_D5', '\U20AC', digits = 0)  %>%
  
  formatPercentage('return_D23', 2)%>%
  formatStyle('return_D23', background = color_from_middle(t2$return_D23,'pink','lightgreen'))%>%
  formatCurrency('ab_return_D23', '\U20AC', digits = 0) %>%
  formatPercentage('CAPM_return_D23', 2)%>%
  formatStyle('CAPM_return_D23', background = color_from_middle(t2$CAPM_return_D23,'pink','lightgreen'))%>%
    formatPercentage('jensen_alpha_D23', 2)%>%
  formatStyle('jensen_alpha_D23', background = color_from_middle(t2$jensen_alpha_D23,'pink','lightgreen'))%>%
  formatCurrency('ab_return_D23', '\U20AC', digits = 0)  %>%
  
  formatPercentage('return_D125', 2)%>%
  formatStyle('return_D125', background = color_from_middle(t2$return_D125,'pink','lightgreen'))%>%
  formatCurrency('ab_return_D125', '\U20AC', digits = 0)   %>%
  formatPercentage('CAPM_return_D125', 2)%>%
  formatStyle('CAPM_return_D125', background = color_from_middle(t2$CAPM_return_D125,'pink','lightgreen'))%>%
  formatPercentage('jensen_alpha_D125', 2)%>%
  formatStyle('jensen_alpha_D125', background = color_from_middle(t2$jensen_alpha_D125,'pink','lightgreen'))%>%
  formatCurrency('ab_return_D125', '\U20AC', digits = 0)  %>%
  
  formatPercentage('return_D250', 2)%>%
  formatStyle('return_D250', background = color_from_middle(t2$return_D250,'pink','lightgreen'))%>%
  formatCurrency('ab_return_D250', '\U20AC', digits = 0) %>%
  formatPercentage('CAPM_return_D250', 2)%>%
  formatStyle('CAPM_return_D250', background = color_from_middle(t2$CAPM_return_D250,'pink','lightgreen'))%>%
  formatPercentage('jensen_alpha_D250', 2)%>%
  formatStyle('jensen_alpha_D250', background = color_from_middle(t2$jensen_alpha_D250,'pink','lightgreen'))%>%
  formatCurrency('ab_return_D250', '\U20AC', digits = 0)  
```




```{r include = TRUE, echo=FALSE}
replace(dp$position, is.na(dp$position),0) %>% 
  subset(dp$position$SharePortfolio==0 | is.na(dp$position$SharePortfolio),
                      select=c('Name','Category',
                  'SharePortfolio', 
                  'Value',
                  'ab_return_D1',
                  'return_D1',
                  'CAPM_return_D1',
                  'jensen_alpha_D1',
                  'ab_return_D5',
                  'return_D5',
                  'CAPM_return_D5',
                  'jensen_alpha_D5',
                  'ab_return_D23',
                  'return_D23',
                  'CAPM_return_D23',
                  'jensen_alpha_D23',
                  'ab_return_D125',
                  'return_D125',
                  'CAPM_return_D125',
                  'jensen_alpha_D125',
                  'ab_return_D250',
                  'return_D250',
                  'CAPM_return_D250',
                  'jensen_alpha_D250')) -> t2

t2 %>%
  datatable(extensions = 'Buttons', options = list(pageLength = 100,
                                                   columnDefs = list(list(visible=FALSE, targets=c(6:18))),
                                                   dom = 'Bfrtip',
                                                   buttons = list('copy', 'csv', 'excel', 'pdf', 'print',
                                                                  list(extend = 'colvis',visible=F, targets= 0))
  )) %>%
  formatCurrency('Value', '\U20AC', digits = 0) %>%
  formatPercentage('SharePortfolio', 1) %>%
  formatStyle('SharePortfolio', background = color_from_middle(t2$SharePortfolio,'lightblue','lightblue')) %>%
  formatPercentage('return_D1', 2) %>%
  formatStyle('return_D1', background = color_from_middle(t2$return_D1,'pink','lightgreen'))%>%
  formatPercentage('CAPM_return_D1', 2)%>%
  formatStyle('CAPM_return_D1', background = color_from_middle(t2$CAPM_return_D1,'pink','lightgreen'))%>%
  formatPercentage('jensen_alpha_D1', 2)%>%
  formatStyle('jensen_alpha_D1', background = color_from_middle(t2$jensen_alpha_D1,'pink','lightgreen'))%>%
  formatCurrency('ab_return_D1', '\U20AC', digits = 0)  %>%
  
  formatPercentage('return_D5', 2)%>%
  formatStyle('return_D5', background = color_from_middle(t2$return_D5,'pink','lightgreen'))%>%
  formatCurrency('ab_return_D5', '\U20AC', digits = 0)  %>%
  formatPercentage('CAPM_return_D5', 2)%>%
  formatStyle('CAPM_return_D5', background = color_from_middle(t2$CAPM_return_D5,'pink','lightgreen'))%>%
    formatPercentage('jensen_alpha_D5', 2)%>%
  formatStyle('jensen_alpha_D5', background = color_from_middle(t2$jensen_alpha_D5,'pink','lightgreen'))%>%
  formatCurrency('ab_return_D5', '\U20AC', digits = 0)  %>%
  
  formatPercentage('return_D23', 2)%>%
  formatStyle('return_D23', background = color_from_middle(t2$return_D23,'pink','lightgreen'))%>%
  formatCurrency('ab_return_D23', '\U20AC', digits = 0) %>%
  formatPercentage('CAPM_return_D23', 2)%>%
  formatStyle('CAPM_return_D23', background = color_from_middle(t2$CAPM_return_D23,'pink','lightgreen'))%>%
    formatPercentage('jensen_alpha_D23', 2)%>%
  formatStyle('jensen_alpha_D23', background = color_from_middle(t2$jensen_alpha_D23,'pink','lightgreen'))%>%
  formatCurrency('ab_return_D23', '\U20AC', digits = 0)  %>%
  
  formatPercentage('return_D125', 2)%>%
  formatStyle('return_D125', background = color_from_middle(t2$return_D125,'pink','lightgreen'))%>%
  formatCurrency('ab_return_D125', '\U20AC', digits = 0)   %>%
  formatPercentage('CAPM_return_D125', 2)%>%
  formatStyle('CAPM_return_D125', background = color_from_middle(t2$CAPM_return_D125,'pink','lightgreen'))%>%
  formatPercentage('jensen_alpha_D125', 2)%>%
  formatStyle('jensen_alpha_D125', background = color_from_middle(t2$jensen_alpha_D125,'pink','lightgreen'))%>%
  formatCurrency('ab_return_D125', '\U20AC', digits = 0)  %>%
  
  formatPercentage('return_D250', 2)%>%
  formatStyle('return_D250', background = color_from_middle(t2$return_D250,'pink','lightgreen'))%>%
  formatCurrency('ab_return_D250', '\U20AC', digits = 0) %>%
  formatPercentage('CAPM_return_D250', 2)%>%
  formatStyle('CAPM_return_D250', background = color_from_middle(t2$CAPM_return_D250,'pink','lightgreen'))%>%
  formatPercentage('jensen_alpha_D250', 2)%>%
  formatStyle('jensen_alpha_D250', background = color_from_middle(t2$jensen_alpha_D250,'pink','lightgreen'))%>%
  formatCurrency('ab_return_D250', '\U20AC', digits = 0)  
```


</center>